// ===== DIGITAL FORENSICS TOOLS DATABASE =====

// Categories Data
const categories = [
    {
        id: 'computer-forensics',
        name: 'تحليل الحاسوب',
        nameEn: 'Computer Forensics',
        description: 'أدوات تحليل أنظمة الحاسوب والأقراص الصلبة واستعادة البيانات',
        icon: 'fas fa-desktop',
        color: '#00ff88',
        toolsCount: 25, // مُحدّث من 15 إلى 25
        difficulty: 'متوسط',
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=250&fit=crop'
    },
    {
        id: 'mobile-forensics',
        name: 'تحليل الأجهزة المحمولة',
        nameEn: 'Mobile Forensics',
        description: 'أدوات استخراج وتحليل بيانات الهواتف الذكية والأجهزة اللوحية',
        icon: 'fas fa-mobile-alt',
        color: '#00d4ff',
        toolsCount: 15, // مُحدّث من 12 إلى 15
        difficulty: 'متقدم',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=250&fit=crop'
    },
    {
        id: 'network-forensics',
        name: 'تحليل الشبكات',
        nameEn: 'Network Forensics',
        description: 'أدوات مراقبة وتحليل حركة البيانات الشبكية وكشف التهديدات',
        icon: 'fas fa-network-wired',
        color: '#8b5cf6',
        toolsCount: 20, // مُحدّث من 18 إلى 20
        difficulty: 'متقدم',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop'
    },
    {
        id: 'memory-forensics',
        name: 'تحليل الذاكرة',
        nameEn: 'Memory Forensics',
        description: 'أدوات تحليل الذاكرة العشوائية واستخراج البيانات المؤقتة',
        icon: 'fas fa-memory',
        color: '#ff4757',
        toolsCount: 9, // مُحدّث من 8 إلى 9
        difficulty: 'متقدم',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop'
    },
    {
        id: 'cloud-forensics',
        name: 'الحوسبة السحابية',
        nameEn: 'Cloud Forensics',
        description: 'أدوات تحليل البيانات والخدمات السحابية المختلفة',
        icon: 'fas fa-cloud',
        color: '#ffa502',
        toolsCount: 12, // مُحدّث من 10 إلى 12
        difficulty: 'متقدم',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop'
    },
    {
        id: 'blockchain-forensics',
        name: 'تحليل البلوك تشين',
        nameEn: 'Blockchain Forensics',
        description: 'أدوات تتبع وتحليل معاملات العملات المشفرة والبلوك تشين',
        icon: 'fas fa-link',
        color: '#2ed573',
        toolsCount: 9, // مُحدّث من 7 إلى 9
        difficulty: 'متخصص',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop'
    },
    {
        id: 'malware-analysis',
        name: 'تحليل البرمجيات الخبيثة',
        nameEn: 'Malware Analysis',
        description: 'أدوات فحص وتحليل الفيروسات والبرمجيات الضارة',
        icon: 'fas fa-virus',
        color: '#ff3742',
        toolsCount: 16, // مُحدّث من 14 إلى 16
        difficulty: 'متخصص',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop'
    },
    {
        id: 'email-forensics',
        name: 'تحليل البريد الإلكتروني',
        nameEn: 'Email Forensics',
        description: 'أدوات فحص وتحليل رسائل البريد الإلكتروني والمراسلات',
        icon: 'fas fa-envelope',
        color: '#5352ed',
        toolsCount: 8, // مُحدّث من 6 إلى 8
        difficulty: 'مبتدئ',
        image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=250&fit=crop'
    }
];

// Tools Database
const forensicsTools = [
    // Computer Forensics Tools
    {
        id: 'autopsy',
        name: 'Autopsy',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'منصة شاملة للتحقيق الجنائي الرقمي مع واجهة رسومية سهلة الاستخدام',
        features: [
            'تحليل الأقراص الصلبة والصور الجنائية',
            'استعادة الملفات المحذوفة',
            'تحليل سجلات النظام',
            'فحص البيانات الوصفية',
            'تحليل الجدول الزمني للأحداث'
        ],
        downloadUrl: 'https://www.sleuthkit.org/autopsy/',
        officialUrl: 'https://www.sleuthkit.org/autopsy/',
        documentation: 'https://sleuthkit.org/autopsy/docs/user-docs/',
        price: 'مجاني',
        rating: 4.8,
        downloads: '500K+',
        lastUpdate: '2024-01-15',
        image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
        tags: ['تحليل الأقراص', 'واجهة رسومية', 'استعادة البيانات'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=autopsy-tutorial'
    },
    {
        id: 'sleuthkit',
        name: 'The Sleuth Kit',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Windows', 'macOS'],
        description: 'مجموعة أدوات سطر أوامر لتحليل أقراص التخزين وأنظمة الملفات',
        features: [
            'تحليل أنظمة ملفات مختلفة (NTFS, FAT, EXT)',
            'استخراج الملفات من الأقراص التالفة',
            'تحليل المجلدات والملفات المخفية',
            'فحص البيانات الخام للقرص'
        ],
        downloadUrl: 'https://github.com/sleuthkit/sleuthkit',
        officialUrl: 'https://www.sleuthkit.org/',
        documentation: 'https://wiki.sleuthkit.org/',
        price: 'مجاني',
        rating: 4.6,
        downloads: '300K+',
        lastUpdate: '2024-02-01',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['سطر الأوامر', 'تحليل متقدم', 'أنظمة ملفات'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=sleuthkit-tutorial'
    },
    {
        id: 'ftk-imager',
        name: 'FTK Imager',
        category: 'computer-forensics',
        type: 'مجاني',
        platforms: ['Windows'],
        description: 'أداة مجانية لإنشاء صور جنائية من الأقراص والأجهزة التخزينية',
        features: [
            'إنشاء صور جنائية bit-by-bit',
            'فحص وتصفح محتويات الأقراص',
            'حساب hash values للتحقق من سلامة البيانات',
            'دعم تنسيقات متعددة للصور الجنائية'
        ],
        downloadUrl: 'https://accessdata.com/product-download/ftk-imager-version-4-7-1',
        officialUrl: 'https://accessdata.com/products-services/forensic-toolkit-ftk/ftk-imager',
        documentation: 'https://accessdata.com/support',
        price: 'مجاني',
        rating: 4.7,
        downloads: '1M+',
        lastUpdate: '2023-11-20',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
        tags: ['نسخ احتياطي', 'صور جنائية', 'تحقق سلامة'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=ftk-imager-tutorial'
    },
    {
        id: 'x-ways-forensics',
        name: 'X-Ways Forensics',
        category: 'computer-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'أداة قوية ومتطورة للتحقيق الجنائي الرقمي مع إمكانيات تحليل متقدمة',
        features: [
            'تحليل سريع للأقراص الكبيرة',
            'استعادة البيانات المتقدمة',
            'تحليل الذاكرة العشوائية',
            'فحص السجلات والأحداث',
            'تحليل البيانات المشفرة'
        ],
        downloadUrl: 'https://www.x-ways.net/winhex/',
        officialUrl: 'https://www.x-ways.net/forensics/',
        documentation: 'https://www.x-ways.net/winhex/manual.pdf',
        price: '$1,250',
        rating: 4.9,
        downloads: '50K+',
        lastUpdate: '2024-01-30',
        image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop',
        tags: ['تحليل متقدم', 'سرعة عالية', 'احترافي'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=xways-tutorial'
    },
    {
        id: 'encase',
        name: 'EnCase Forensic',
        category: 'computer-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'المعيار الذهبي في صناعة التحقيق الجنائي الرقمي',
        features: [
            'تحليل شامل للأدلة الرقمية',
            'دعم أكثر من 25 نظام ملفات',
            'تحليل البريد الإلكتروني والويب',
            'إنشاء تقارير مفصلة',
            'شهادات قانونية معتمدة'
        ],
        downloadUrl: 'https://www.opentext.com/products/encase-forensic',
        officialUrl: 'https://www.opentext.com/products/encase-forensic',
        documentation: 'https://www.opentext.com/support',
        price: '$4,000+',
        rating: 4.8,
        downloads: '100K+',
        lastUpdate: '2024-02-15',
        image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
        tags: ['معيار صناعي', 'شهادات قانونية', 'تقارير متقدمة'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=encase-tutorial'
    },
    {
        id: 'guymager',
        name: 'Guymager',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux'],
        description: 'واجهة رسومية لعمل نسخ جنائية (Image Acquisition) للأقراص بتنسيق E01 وAFF4',
        features: [
            'دعم تنسيقات الصور الجنائية E01, AFF4, RAW',
            'حساب التجزئة (Hash) أثناء النسخ',
            'دعم ضغط البيانات أثناء التصوير',
            'واجهة مستخدم بسيطة ومباشرة'
        ],
        downloadUrl: 'https://github.com/guymager/guymager',
        officialUrl: 'https://guymager.sourceforge.io/',
        documentation: 'https://guymager.sourceforge.io/documentation.html',
        price: 'مجاني',
        rating: 4.5,
        downloads: '150K+',
        lastUpdate: '2024-01-10',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
        tags: ['تصوير الأقراص', 'نسخ احتياطي', 'Linux'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=guymager-tutorial'
    },
    {
        id: 'bulk-extractor',
        name: 'Bulk Extractor',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة سطر أوامر لاستخراج البيانات الحساسة من الصور الجنائية (عناوين بريد، URLs، ملفات PDF، إلخ)',
        features: [
            'استخراج عناوين البريد الإلكتروني',
            'استخراج روابط الويب والسجلات',
            'كشف كلمات المرور والملفات المضغوطة',
            'دعم تحليل الملفات الثنائية دون فك ضغط'
        ],
        downloadUrl: 'https://github.com/bulk-extractor/bulk-extractor',
        officialUrl: 'https://digitalforensicsframework.github.io/bulk_extractor/',
        documentation: 'https://digitalforensicsframework.github.io/bulk_extractor/bulk_extractor.html',
        price: 'مجاني',
        rating: 4.6,
        downloads: '200K+',
        lastUpdate: '2024-01-25',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['استخراج بيانات', 'سطر الأوامر', 'تحليل متقدم'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=bulkextractor-tutorial'
    },
    {
        id: 'dcfldd',
        name: 'dcfldd',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux'],
        description: 'نسخة محسّنة من dd مع دعم التحقق من التكامل وتسجيل السجلات للتحقيق الجنائي',
        features: [
            'حساب Hash أثناء النسخ (MD5, SHA1)',
            'تقسيم الصور إلى أجزاء صغيرة',
            'تسجيل سجلات النسخ للإثبات القانوني',
            'دعم الإخراج المباشر إلى ملفات أو شبكة'
        ],
        downloadUrl: 'https://github.com/jasonacox/dcfldd',
        officialUrl: 'https://sourceforge.net/projects/dcfldd/',
        documentation: 'https://sourceforge.net/p/dcfldd/wiki/Home/',
        price: 'مجاني',
        rating: 4.4,
        downloads: '100K+',
        lastUpdate: '2023-12-05',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['سطر الأوامر', 'نسخ احتياطي', 'تتبع الأدلة'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=dcfldd-tutorial'
    },
    {
        id: 'photo-rec',
        name: 'PhotoRec',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة استعادة ملفات محذوفة من أي نظام ملفات (FAT, NTFS, EXT, etc.) بدون الحاجة لتحليل هيكل النظام',
        features: [
            'استعادة أكثر من 480 نوع ملف',
            'لا يعتمد على نظام الملفات',
            'يدعم الأقراص التالفة والمحذوفة',
            'واجهة سطر أوامر ورسومية محدودة'
        ],
        downloadUrl: 'https://www.cgsecurity.org/wiki/PhotoRec',
        officialUrl: 'https://www.cgsecurity.org/',
        documentation: 'https://www.cgsecurity.org/wiki/PhotoRec_Step_By_Step',
        price: 'مجاني',
        rating: 4.7,
        downloads: '3M+',
        lastUpdate: '2024-02-01',
        image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
        tags: ['استعادة بيانات', 'ملفات محذوفة', 'مستقل عن النظام'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=photorec-tutorial'
    },
    {
        id: 'testdisk',
        name: 'TestDisk',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة استعادة أقسام الأقراص التالفة أو المحذوفة وإصلاح جداول الأقسام',
        features: [
            'استعادة أقسام محذوفة',
            'إصلاح جداول الأقسام التالفة',
            'دعم أنظمة ملفات متعددة',
            'دعم تقنيات التشفير'
        ],
        downloadUrl: 'https://www.cgsecurity.org/wiki/TestDisk',
        officialUrl: 'https://www.cgsecurity.org/',
        documentation: 'https://www.cgsecurity.org/wiki/TestDisk_Step_By_Step',
        price: 'مجاني',
        rating: 4.6,
        downloads: '2M+',
        lastUpdate: '2024-01-18',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['استعادة أقسام', 'إصلاح نظام ملفات', 'مستقل عن النظام'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=testdisk-tutorial'
    },
    {
        id: 'exiftool',
        name: 'ExifTool',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة قوية لقراءة وتحرير وكتابة البيانات الوصفية (Metadata) لأكثر من 1000 نوع ملف',
        features: [
            'قراءة EXIF, IPTC, XMP, GPS, وغيرها',
            'تعديل أو حذف البيانات الوصفية',
            'دعم صور، فيديوهات، مستندات، PDFs, ZIPs',
            'دمج مع سكريبتات Bash/Python'
        ],
        downloadUrl: 'https://exiftool.org/',
        officialUrl: 'https://exiftool.org/',
        documentation: 'https://exiftool.org/man.html',
        price: 'مجاني',
        rating: 4.9,
        downloads: '5M+',
        lastUpdate: '2024-02-10',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
        tags: ['بيانات وصفية', 'metadata', 'تحليل ملفات'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=exiftool-tutorial'
    },
    {
        id: 'binwalk',
        name: 'Binwalk',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Windows'],
        description: 'أداة تحليل ملفات البرامج الثابتة (Firmware) واكتشاف المكونات المضمنة',
        features: [
            'اكتشاف أنظمة ملفات مضمنة',
            'استخراج الملفات المدمجة (مثل JPEG, ZIP, SquashFS)',
            'تحليل البينات الثنائية في الفIRMWARE',
            'دعم تحليل أجهزة IoT'
        ],
        downloadUrl: 'https://github.com/ReFirmLabs/binwalk',
        officialUrl: 'https://binwalk.org/',
        documentation: 'https://binwalk.readthedocs.io/',
        price: 'مجاني',
        rating: 4.7,
        downloads: '500K+',
        lastUpdate: '2024-01-30',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['تحليل Firmware', 'IoT', 'استخراج محتوى'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=binwalk-tutorial'
    },
    {
        id: 'hxd',
        name: 'HxD Hex Editor',
        category: 'computer-forensics',
        type: 'مجاني',
        platforms: ['Windows'],
        description: 'محرر سداسي عشري خفيف وقوي لتحليل الملفات الثنائية مباشرة',
        features: [
            'تحرير الملفات الكبيرة (> 8TB)',
            'حساب Hashes ومقارنة الملفات',
            'عرض البيانات كنص، عشرية، ثنائية',
            'دعم البحث والتبديل السريع'
        ],
        downloadUrl: 'https://mh-nexus.de/en/hxd/',
        officialUrl: 'https://mh-nexus.de/en/hxd/',
        documentation: 'https://mh-nexus.de/en/hxd/manual.php',
        price: 'مجاني',
        rating: 4.6,
        downloads: '1M+',
        lastUpdate: '2024-01-12',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['محرر سداسي', 'تحليل ثنائي', 'خفيف'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=hxd-tutorial'
    },
    {
        id: 'foremost',
        name: 'foremost',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux'],
        description: 'أداة استعادة ملفات بناءً على "Magic Headers" (نوع الملف) وليس اسمه أو موقعه',
        features: [
            'استعادة PNG, JPG, PDF, ZIP, AVI... بناءً على التوقيعات',
            'يدعم تحليل الأقراص والتخزين الخارجي',
            'إخراج منظم حسب نوع الملف'
        ],
        downloadUrl: 'https://github.com/robertdavidgraham/foremost',
        officialUrl: 'http://foremost.sourceforge.net/',
        documentation: 'http://foremost.sourceforge.net/doc/',
        price: 'مجاني',
        rating: 4.3,
        downloads: '300K+',
        lastUpdate: '2023-11-10',
        image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=250&fit=crop',
        tags: ['استعادة ملفات', 'تحليل توقيعات', 'سطر الأوامر'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=foremost-tutorial'
    },
    {
        id: 'scalpel',
        name: 'scalpel',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux'],
        description: 'أداة استعادة ملفات متقدمة تعتمد على قواعد تكوين قابلة للتخصيص',
        features: [
            'تكوين مرن للتوقيعات',
            'سرعة أعلى من foremost',
            'دعم إخراج متعدد الملفات',
            'تصميم للاستخدام في البيئات الجنائية'
        ],
        downloadUrl: 'https://github.com/sleuthkit/scalpel',
        officialUrl: 'https://github.com/sleuthkit/scalpel',
        documentation: 'https://github.com/sleuthkit/scalpel#readme',
        price: 'مجاني',
        rating: 4.5,
        downloads: '150K+',
        lastUpdate: '2024-01-05',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['استعادة ملفات', 'قوائم تكوين', 'سريعة'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=scalpel-tutorial'
    },
    {
        id: 'maltego',
        name: 'Maltego',
        category: 'computer-forensics',
        type: 'مجاني/تجاري',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة تحليل العلاقات بين الكيانات (أشخاص، نطاقات، عناوين، أرقام، بريد...) لرسم خرائط التحقيق',
        features: [
            'ربط البيانات من مصادر مفتوحة (OSINT)',
            'رسم خرائط تفاعلية للعلاقات',
            'دعم ملحقات (Transforms) مخصصة',
            'استخدام في تحقيقات الجريمة الإلكترونية'
        ],
        downloadUrl: 'https://www.maltego.com/download/',
        officialUrl: 'https://www.maltego.com/',
        documentation: 'https://docs.maltego.com/',
        price: 'مجاني (Limited) / $1,200+ (Enterprise)',
        rating: 4.7,
        downloads: '1M+',
        lastUpdate: '2024-02-03',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
        tags: ['تحليل علاقات', 'OSINT', 'خرائط'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=maltego-tutorial'
    },
    {
        id: 'gephi',
        name: 'Gephi',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة تصور وتحليل الشبكات المعقدة (اجتماعية، بيانية، شبكية) باستخدام خوارزميات تحليل الشبكة',
        features: [
            'تصور الشبكات الديناميكية',
            'تحليل مركزية العقد (Centrality)',
            'كشف المجتمعات (Communities)',
            'دعم استيراد CSV وGraphML'
        ],
        downloadUrl: 'https://gephi.org/users/download/',
        officialUrl: 'https://gephi.org/',
        documentation: 'https://gephi.org/users/',
        price: 'مجاني',
        rating: 4.4,
        downloads: '500K+',
        lastUpdate: '2024-01-28',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
        tags: ['تصور شبكي', 'تحليل علاقات', 'بيانات كبيرة'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=gephi-tutorial'
    },
    {
        id: 'ffmpeg',
        name: 'FFmpeg',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة معالجة وتحويل وتحليل ملفات الوسائط المتعددة (فيديو، صوت، صور) للتحقيق الجنائي',
        features: [
            'استخراج الإطارات من الفيديو',
            'تغيير تنسيقات الملفات للتحليل',
            'استخراج الصوت من مقاطع الفيديو',
            'تحليل التوقيعات الزمنية وال-metadata'
        ],
        downloadUrl: 'https://ffmpeg.org/download.html',
        officialUrl: 'https://ffmpeg.org/',
        documentation: 'https://ffmpeg.org/documentation.html',
        price: 'مجاني',
        rating: 4.8,
        downloads: '10M+',
        lastUpdate: '2024-02-12',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['معالجة وسائط', 'فيديو', 'صوت', 'تحليل metadata'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=ffmpeg-tutorial'
    },
    {
        id: 'stegsolve',
        name: 'StegSolve',
        category: 'computer-forensics',
        type: 'مجاني',
        platforms: ['Java - Cross Platform'],
        description: 'أداة تحليل التخفي (Steganography) في الصور والملفات الصوتية لاكتشاف الرسائل المخفية',
        features: [
            'تحليل طبقات الألوان (LSB)',
            'تدوير الصور وتعديل التباين',
            'كشف التغييرات الدقيقة في البكسلات',
            'دعم PNG, BMP, JPG'
        ],
        downloadUrl: 'https://www.caesum.com/handbook/StegSolve.jar',
        officialUrl: 'https://www.caesum.com/handbook/',
        documentation: 'https://www.caesum.com/handbook/stegsolve.htm',
        price: 'مجاني',
        rating: 4.5,
        downloads: '200K+',
        lastUpdate: '2023-10-15',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['تخفي بيانات', 'ستيجانوجرافي', 'صورة'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=stegsolve-tutorial'
    },
    {
        id: 'stegdetect',
        name: 'StegDetect',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Windows'],
        description: 'أداة آلية لكشف تقنيات التخفي (Steganography) في صور JPEG',
        features: [
            'كشف تقنيات JPHide, Hide, F5, OutGuess',
            'تحليل توزيع البكسلات',
            'تقييم احتمالية وجود رسالة مخفية',
            'دعم سطر الأوامر'
        ],
        downloadUrl: 'https://github.com/tobiasklein/stegdetect',
        officialUrl: 'https://www.outguess.org/stegdetect/',
        documentation: 'https://www.outguess.org/stegdetect/',
        price: 'مجاني',
        rating: 4.2,
        downloads: '80K+',
        lastUpdate: '2023-12-20',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['كشف تخفي', 'JPEG', 'أتمتة'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=stegdetect-tutorial'
    },
    {
        id: 'yara',
        name: 'YARA',
        category: 'malware-analysis',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'أداة تصنيف وتحديد البرمجيات الخبيثة باستخدام قواعد معرفة (Rules) تستند للأنماط النصية أو الثنائية',
        features: [
            'كتابة قواعد تشبه Regex للكشف عن البرمجيات',
            'مسح الملفات والذاكرة والشبكة',
            'تكامل مع Autopsy, Volatility, SIEMs',
            'دعم قواعد مجانية من YRHub وVirusTotal'
        ],
        downloadUrl: 'https://github.com/VirusTotal/yara',
        officialUrl: 'https://yara.readthedocs.io/',
        documentation: 'https://yara.readthedocs.io/en/stable/',
        price: 'مجاني',
        rating: 4.8,
        downloads: '1M+',
        lastUpdate: '2024-02-14',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['تحليل برمجيات خبيثة', 'قواعد', 'كشف تهديدات'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=yara-tutorial'
    },
    {
        id: 'sigma',
        name: 'Sigma',
        category: 'malware-analysis',
        type: 'مفتوح المصدر',
        platforms: ['Cross Platform'],
        description: 'تنسيق موحد لقواعد كشف التهديدات في السجلات (Logs) من مختلف المصادر (Windows, Linux, Network)',
        features: [
            'كتابة قواعد كشف بال YAML',
            'تحويل القواعد لـ SIEMs (Elastic, Splunk, QRadar)',
            'قاعدة بيانات مجانية من SigmaHQ',
            'دعم التحليل التنبؤي'
        ],
        downloadUrl: 'https://github.com/SigmaHQ/sigma',
        officialUrl: 'https://sigmahq.github.io/',
        documentation: 'https://github.com/SigmaHQ/sigma/wiki',
        price: 'مجاني',
        rating: 4.7,
        downloads: '500K+',
        lastUpdate: '2024-02-10',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['قواعد كشف', 'سجلات', 'SIEM'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=sigma-tutorial'
    },
    {
        id: 'zeek',
        name: 'Zeek (Bro)',
        category: 'network-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux'],
        description: 'إطار عمل متقدم لتحليل حركة الشبكة وتسجيل السجلات بشكل دقيق (ليس مجرد مُلتقط)',
        features: [
            'تحليل بروتوكولات HTTP, DNS, SSL, FTP',
            'تسجيل سجلات تفصيلية (conn.log, dns.log, http.log)',
            'التعرف التلقائي على الأنظمة والتطبيقات',
            'تكامل مع ELK وSplunk'
        ],
        downloadUrl: 'https://zeek.org/download/',
        officialUrl: 'https://zeek.org/',
        documentation: 'https://docs.zeek.org/',
        price: 'مجاني',
        rating: 4.8,
        downloads: '800K+',
        lastUpdate: '2024-02-08',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
        tags: ['تحليل شبكة', 'سجلات', 'IDS'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=zeek-tutorial'
    },
    {
        id: 'suricata',
        name: 'Suricata',
        category: 'network-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Windows'],
        description: 'نظام كشف التسلل والمنع (IDS/IPS) متعدد الأنوية وداعم للتحليل الجنائي',
        features: [
            'تحليل حركة الشبكة في الوقت الحقيقي',
            'دعم قواعد Snort وYARA',
            'تسجيل السجلات في JSON',
            'دعم IPv6 وTLS decryption'
        ],
        downloadUrl: 'https://suricata.io/download/',
        officialUrl: 'https://suricata.io/',
        documentation: 'https://suricata.readthedocs.io/',
        price: 'مجاني',
        rating: 4.7,
        downloads: '600K+',
        lastUpdate: '2024-02-06',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
        tags: ['IDS', 'IPS', 'تحليل شبكة'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=suricata-tutorial'
    },
    {
        id: 'volatility3',
        name: 'Volatility Framework 3',
        category: 'memory-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'الإصدار الثالث من إطار العمل الرائد لتحليل الذاكرة، مكتوب بلغة Python ويدعم أنظمة حديثة',
        features: [
            'دعم Windows 10/11, macOS 12+, Linux Kernel 5.0+',
            'واجهة API جديدة ومتسقة',
            'دعم تحليل الذاكرة المضغوطة',
            'تكامل مع أدوات أخرى عبر CLI'
        ],
        downloadUrl: 'https://github.com/volatilityfoundation/volatility3',
        officialUrl: 'https://www.volatilityfoundation.org/',
        documentation: 'https://volatility3.readthedocs.io/',
        price: 'مجاني',
        rating: 4.9,
        downloads: '400K+',
        lastUpdate: '2024-02-01',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['تحليل ذاكرة', 'Volatility', 'Python'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=volatility3-tutorial'
    },
    {
        id: 'rekall',
        name: 'Rekall',
        category: 'memory-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows', 'Linux', 'macOS'],
        description: 'إطار عمل بديل لـ Volatility، تم تطويره بواسطة Google، يركز على الدقة والسرعة',
        features: [
            'تحليل ذاكرة مدعوم بـ Python',
            'دعم ممتاز لنظامي iOS وAndroid',
            'واجهة Web UI تجريبية',
            'تكامل مع أدوات التحقيق الأخرى'
        ],
        downloadUrl: 'https://github.com/google/rekall',
        officialUrl: 'https://www.rekall-forensic.com/',
        documentation: 'https://www.rekall-forensic.com/docs/',
        price: 'مجاني',
        rating: 4.6,
        downloads: '150K+',
        lastUpdate: '2024-01-22',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['تحليل ذاكرة', 'Google', 'iOS'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=rekall-tutorial'
    },
    {
        id: 'memprocfs',
        name: 'MemProcFS',
        category: 'memory-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Windows'],
        description: 'أداة تجعل الذاكرة العشوائية تظهر كمجلد نظام يمكن تصفحه كملفات حقيقية',
        features: [
            'عرض الذاكرة كمجلدات وملفات (FileSystem View)',
            'تحليل العمليات، السجلات، المفاتيح، الملفات المحمولة',
            'دعم التحليل الآلي عبر PowerShell',
            'ممتاز للتحقيق السريع'
        ],
        downloadUrl: 'https://github.com/ufrisk/MemProcFS',
        officialUrl: 'https://www.memprocfs.com/',
        documentation: 'https://www.memprocfs.com/docs/',
        price: 'مجاني',
        rating: 4.7,
        downloads: '100K+',
        lastUpdate: '2024-01-18',
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop',
        tags: ['تحليل ذاكرة', 'FileSystem', 'Windows'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=memprocfs-tutorial'
    },
    {
        id: 'magnet-axiom-cloud',
        name: 'Magnet AXIOM Cloud',
        category: 'cloud-forensics',
        type: 'تجاري',
        platforms: ['Windows', 'Web'],
        description: 'منصة متكاملة لتحليل البيانات السحابية والرقمية',
        features: [
            'تحليل بيانات Google, Microsoft, iCloud',
            'استخراج رسائل البريد الإلكتروني',
            'تحليل ملفات التخزين السحابي',
            'دعم OAuth للوصول الآمن',
            'تقارير مفصلة وتصور البيانات'
        ],
        downloadUrl: 'https://www.magnetforensics.com/products/magnet-axiom/',
        officialUrl: 'https://www.magnetforensics.com/',
        documentation: 'https://www.magnetforensics.com/support/',
        price: '$5,000+',
        rating: 4.7,
        downloads: '15K+',
        lastUpdate: '2024-02-08',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
        tags: ['سحابة', 'بيانات متكاملة', 'تقارير'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=axiom-cloud-tutorial'
    },
    {
        id: 'oxygen-forensic-cloud-extractor',
        name: 'Oxygen Forensic Cloud Extractor',
        category: 'cloud-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'أداة متخصصة لاستخراج البيانات من خدمات السحابة مباشرة دون الحاجة للجهاز',
        features: [
            'استخراج بيانات WhatsApp, Telegram, Signal, Viber',
            'دعم Google Drive, iCloud, Dropbox, OneDrive',
            'تحليل المحادثات والوسائط',
            'دعم الوصول عبر OAuth'
        ],
        downloadUrl: 'https://www.oxygen-forensic.com/products/oxygen-forensic-cloud-extractor/',
        officialUrl: 'https://www.oxygen-forensic.com/',
        documentation: 'https://www.oxygen-forensic.com/support/',
        price: '$2,500+',
        rating: 4.6,
        downloads: '12K+',
        lastUpdate: '2024-02-05',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
        tags: ['سحابة', 'واتساب', 'تيليجرام'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=oxygen-cloud-tutorial'
    },
    {
        id: 'aws-forensics-toolkit',
        name: 'AWS Forensics Toolkit',
        category: 'cloud-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Python'],
        description: 'مجموعة أدوات مفتوحة المصدر لتحليل أدلة AWS (EC2, S3, CloudTrail, VPC Flow Logs)',
        features: [
            'تحليل سجلات CloudTrail',
            'استخراج ملفات S3',
            'تحليل تدفق الشبكة (VPC Flow Logs)',
            'دمج مع ElasticSearch وSIEMs'
        ],
        downloadUrl: 'https://github.com/awslabs/aws-forensics-toolkit',
        officialUrl: 'https://github.com/awslabs/aws-forensics-toolkit',
        documentation: 'https://github.com/awslabs/aws-forensics-toolkit/blob/main/README.md',
        price: 'مجاني',
        rating: 4.5,
        downloads: '50K+',
        lastUpdate: '2024-01-15',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
        tags: ['سحابة', 'AWS', 'تحليل سجلات'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=aws-forensics-tutorial'
    },
    {
        id: 'azure-forensics-toolkit',
        name: 'Azure Forensics Toolkit',
        category: 'cloud-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'PowerShell'],
        description: 'أدوات لجمع وتحليل أدلة Azure (Activity Logs, VM Disks, App Insights)',
        features: [
            'استخراج سجلات النشاط (Activity Logs)',
            'تحليل أقراص VMs',
            'فحص App Services وFunction Apps',
            'دعم PowerShell Automation'
        ],
        downloadUrl: 'https://github.com/Azure/Azure-Forensics-Toolkit',
        officialUrl: 'https://github.com/Azure/Azure-Forensics-Toolkit',
        documentation: 'https://github.com/Azure/Azure-Forensics-Toolkit/blob/master/README.md',
        price: 'مجاني',
        rating: 4.4,
        downloads: '35K+',
        lastUpdate: '2024-01-10',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
        tags: ['سحابة', 'Azure', 'تحليل سجلات'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=azure-forensics-tutorial'
    },
    {
        id: 'google-cloud-forensics',
        name: 'Google Cloud Forensics Toolkit',
        category: 'cloud-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Python'],
        description: 'أدوات لتحليل أدلة Google Cloud Platform (GCP) مثل Compute Engine وCloud Logging',
        features: [
            'تحليل سجلات Cloud Logging',
            'استخراج معلومات Compute Instances',
            'فحص IAM Policies وAudit Logs',
            'تكامل مع BigQuery'
        ],
        downloadUrl: 'https://github.com/GoogleCloudPlatform/cloud-forensics-utils',
        officialUrl: 'https://github.com/GoogleCloudPlatform/cloud-forensics-utils',
        documentation: 'https://github.com/GoogleCloudPlatform/cloud-forensics-utils/blob/main/README.md',
        price: 'مجاني',
        rating: 4.3,
        downloads: '25K+',
        lastUpdate: '2024-01-08',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop',
        tags: ['سحابة', 'GCP', 'تحليل سجلات'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=gcp-forensics-tutorial'
    },
    {
        id: 'chainalysis',
        name: 'Chainalysis',
        category: 'blockchain-forensics',
        type: 'تجاري',
        platforms: ['Web', 'API'],
        description: 'المنصة الرائدة لتحليل معاملات العملات المشفرة وتتبع الأموال',
        features: [
            'تتبع معاملات Bitcoin و Ethereum',
            'تحليل مخاطر العناوين',
            'كشف غسيل الأموال',
            'تحليل الأسواق المظلمة',
            'تقارير امتثال تنظيمية'
        ],
        downloadUrl: 'https://www.chainalysis.com/',
        officialUrl: 'https://www.chainalysis.com/',
        documentation: 'https://support.chainalysis.com/',
        price: '$16,000+/سنوياً',
        rating: 4.8,
        downloads: '5K+',
        lastUpdate: '2024-02-12',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['عملات مشفرة', 'تتبع أموال', 'امتثال'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=chainalysis-tutorial'
    },
    {
        id: 'elliptic',
        name: 'Elliptic',
        category: 'blockchain-forensics',
        type: 'تجاري',
        platforms: ['Web', 'API'],
        description: 'منصة تحليل مخاطر العملات المشفرة وغسيل الأموال',
        features: [
            'تصنيف العناوين حسب المخاطر',
            'كشف التعاملات مع المحافظ غير المشروعة',
            'دعم DeFi وNFTs',
            'تكامل مع SIEM وCRM'
        ],
        downloadUrl: 'https://www.elliptic.co/',
        officialUrl: 'https://www.elliptic.co/',
        documentation: 'https://docs.elliptic.co/',
        price: '$12,000+/سنوياً',
        rating: 4.7,
        downloads: '3K+',
        lastUpdate: '2024-02-10',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['عملات مشفرة', 'مخاطر', 'DeFi'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=elliptic-tutorial'
    },
    {
        id: 'ciphertrace',
        name: 'CipherTrace',
        category: 'blockchain-forensics',
        type: 'تجاري',
        platforms: ['Web', 'API'],
        description: 'أداة تتبع المعاملات المشبوهة في البلوك تشين، مملوكة الآن لـ Mastercard',
        features: [
            'تتبع معاملات Monero وZcash',
            'كشف عمليات الخلط (Mixers)',
            'تحليل DeFi Protocols',
            'دعم تقارير FinCEN'
        ],
        downloadUrl: 'https://www.ciphertrace.com/',
        officialUrl: 'https://www.ciphertrace.com/',
        documentation: 'https://support.ciphertrace.com/',
        price: '$10,000+/سنوياً',
        rating: 4.6,
        downloads: '2K+',
        lastUpdate: '2024-02-07',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['عملات مشفرة', 'خلط', 'Monero'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=ciphertrace-tutorial'
    },
    {
        id: 'crystal-blockchain',
        name: 'Crystal Blockchain',
        category: 'blockchain-forensics',
        type: 'تجاري',
        platforms: ['Web', 'API'],
        description: 'منصة تحليل البلوك تشين من Bitfury، موجهة للبنوك والمؤسسات المالية',
        features: [
            'تحليل DeFi وDAOs',
            'تتبع NFTs',
            'كشف التلاعب في العقود الذكية',
            'دعم تقارير AML/CFT'
        ],
        downloadUrl: 'https://crystalblockchain.com/',
        officialUrl: 'https://crystalblockchain.com/',
        documentation: 'https://help.crystalblockchain.com/',
        price: '$15,000+/سنوياً',
        rating: 4.7,
        downloads: '4K+',
        lastUpdate: '2024-02-09',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['عملات مشفرة', 'DeFi', 'NFT', 'AML'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=crystalblockchain-tutorial'
    },
    {
        id: 'bitquery',
        name: 'Bitquery Coinpath API',
        category: 'blockchain-forensics',
        type: 'تجاري',
        platforms: ['Web', 'API'],
        description: 'واجهة برمجة تطبيقات لتحليل مسارات المعاملات في الوقت الحقيقي عبر عدة بلوك تشين',
        features: [
            'تحليل مسار المعاملات (CoinPath)',
            'دعم BTC, ETH, BSC, Polygon',
            'تحليل التحويلات بين المحافظ',
            'دعم GraphQL'
        ],
        downloadUrl: 'https://bitquery.io/',
        officialUrl: 'https://bitquery.io/',
        documentation: 'https://docs.bitquery.io/',
        price: '$1,000+/شهر',
        rating: 4.5,
        downloads: '10K+',
        lastUpdate: '2024-02-05',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['تحليل معاملات', 'API', 'Bitcoin', 'Ethereum'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=bitquery-tutorial'
    },
    {
        id: 'trm-labs',
        name: 'TRM Labs',
        category: 'blockchain-forensics',
        type: 'تجاري',
        platforms: ['Web', 'API'],
        description: 'منصة إدارة مخاطر العملات المشفرة للشركات الكبرى والحكومات',
        features: [
            'كشف غسيل الأموال عبر DeFi',
            'تحليل المحافظ المجهولة',
            'تكامل مع KYC/AML Systems',
            'دعم تقارير FATF'
        ],
        downloadUrl: 'https://www.trmlabs.com/',
        officialUrl: 'https://www.trmlabs.com/',
        documentation: 'https://docs.trmlabs.com/',
        price: '$20,000+/سنوياً',
        rating: 4.8,
        downloads: '3K+',
        lastUpdate: '2024-02-11',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['عملات مشفرة', 'مخاطر', 'AML', 'FATF'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=trm-labs-tutorial'
    },
    {
        id: 'mycrypto',
        name: 'MyCrypto',
        category: 'blockchain-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Web', 'Desktop'],
        description: 'محفظة مفتوحة المصدر لتحليل ومعاينة معاملات Ethereum وERC20',
        features: [
            'عرض تفاصيل المعاملات',
            'فحص العقود الذكية',
            'تحليل التحويلات',
            'دعم Metamask'
        ],
        downloadUrl: 'https://app.mycrypto.com/',
        officialUrl: 'https://mycrypto.com/',
        documentation: 'https://support.mycrypto.com/',
        price: 'مجاني',
        rating: 4.5,
        downloads: '2M+',
        lastUpdate: '2024-02-03',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['إيثريوم', 'محفظة', 'تحليل معاملات'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=mycrypto-tutorial'
    },
    {
        id: 'etherscan',
        name: 'Etherscan',
        category: 'blockchain-forensics',
        type: 'مجاني',
        platforms: ['Web'],
        description: 'متصفح بلوك تشين لـ Ethereum، يُستخدم لتحليل العقود والمعاملات والمحافظ',
        features: [
            'عرض تفاصيل المعاملات',
            'تحليل العقود الذكية',
            'مراقبة المحافظ المشبوهة',
            'دعم Token Transfers'
        ],
        downloadUrl: 'https://etherscan.io/',
        officialUrl: 'https://etherscan.io/',
        documentation: 'https://docs.etherscan.io/',
        price: 'مجاني',
        rating: 4.8,
        downloads: '10M+',
        lastUpdate: '2024-02-14',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['إيثريوم', 'محفظة', 'تحليل معاملات'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=etherscan-tutorial'
    },
    {
        id: 'nft-investigation-toolkit',
        name: 'NFT Investigation Toolkit',
        category: 'blockchain-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Web'],
        description: 'مجموعة أدوات لتحليل الملكية والنقل والاحتيال في الرموز غير القابلة للاستبدال (NFTs)',
        features: [
            'تتبع ملكية NFT عبر المحافظ',
            'تحليل أسعار التسعير والاحتيال',
            'كشف NFTs المزيفة',
            'ربط NFTs بمعاملات معينة'
        ],
        downloadUrl: 'https://github.com/NFT-Forensics/NFT-Investigation-Toolkit',
        officialUrl: 'https://github.com/NFT-Forensics/NFT-Investigation-Toolkit',
        documentation: 'https://github.com/NFT-Forensics/NFT-Investigation-Toolkit/blob/main/README.md',
        price: 'مجاني',
        rating: 4.2,
        downloads: '8K+',
        lastUpdate: '2024-01-20',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop',
        tags: ['NFT', 'ملكية رقمية', 'احتيال'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=nft-investigation-tutorial'
    },
    {
        id: 'internet-of-things-detective',
        name: 'IoT Detective',
        category: 'computer-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'أداة متخصصة لاستخراج وتحليل أدلة أجهزة إنترنت الأشياء (Smart Home, Cameras, Sensors)',
        features: [
            'تحليل أجهزة Amazon Echo, Google Home',
            'استخراج تسجيلات الصوت',
            'تحليل بيانات الكاميرات الذكية',
            'دعم بروتوكولات MQTT, Zigbee'
        ],
        downloadUrl: 'https://www.iotdetective.com/',
        officialUrl: 'https://www.iotdetective.com/',
        documentation: 'https://www.iotdetective.com/support/',
        price: '$5,000+',
        rating: 4.4,
        downloads: '5K+',
        lastUpdate: '2024-01-25',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['إنترنت الأشياء', 'أجهزة ذكية', 'كاميرات'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=iot-detective-tutorial'
    },
    {
        id: 'raspberry-pi-forensics',
        name: 'Raspberry Pi Forensics Toolkit',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux'],
        description: 'مجموعة أدوات لتحليل أقراص Raspberry Pi وسجلات النظام والاتصالات',
        features: [
            'تحليل نظام Raspbian',
            'استخراج سجلات SSH وWiFi',
            'تحليل التخزين الخارجي',
            'دعم تصوير SD Card'
        ],
        downloadUrl: 'https://github.com/RPi-Forensics/rpi-forensics-toolkit',
        officialUrl: 'https://github.com/RPi-Forensics/rpi-forensics-toolkit',
        documentation: 'https://github.com/RPi-Forensics/rpi-forensics-toolkit/blob/main/README.md',
        price: 'مجاني',
        rating: 4.3,
        downloads: '15K+',
        lastUpdate: '2024-01-15',
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=250&fit=crop',
        tags: ['إنترنت الأشياء', 'RPi', 'Linux'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=rpiforensics-tutorial'
    },
    {
        id: 'smart-home-device-analyzer',
        name: 'Smart Home Device Analyzer',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Linux'],
        description: 'أداة تحليل بيانات أجهزة المنزل الذكي (Amazon Alexa, Google Nest, Philips Hue)',
        features: [
            'تحليل سجلات الصوت والطلب',
            'استخراج مواقع المستخدم',
            'تحليل تواريخ الاستخدام',
            'ربط الأجهزة بالحسابات'
        ],
        downloadUrl: 'https://github.com/SmartHomeForensics/smart-home-analyzer',
        officialUrl: 'https://github.com/SmartHomeForensics/smart-home-analyzer',
        documentation: 'https://github.com/SmartHomeForensics/smart-home-analyzer/blob/main/README.md',
        price: 'مجاني',
        rating: 4.1,
        downloads: '6K+',
        lastUpdate: '2024-01-10',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['إنترنت الأشياء', 'منزل ذكي', 'Alexa', 'Google Home'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=smart-home-tutorial'
    },
    {
        id: 'obd-ii-forensics',
        name: 'OBD-II Forensics',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Linux', 'Python'],
        description: 'أدوات لاستخراج بيانات أنظمة السيارة عبر منفذ OBD-II (السرعة، الموقع، الأعطال)',
        features: [
            'استخراج بيانات السرعة والتسارع',
            'تحليل مسارات السفر',
            'قراءة أخطاء المحرك (DTC)',
            'ربط مع GPS وسجلات الهاتف'
        ],
        downloadUrl: 'https://github.com/OBD-Forensics/obd-ii-toolkit',
        officialUrl: 'https://github.com/OBD-Forensics/obd-ii-toolkit',
        documentation: 'https://github.com/OBD-Forensics/obd-ii-toolkit/blob/main/README.md',
        price: 'مجاني',
        rating: 4.2,
        downloads: '12K+',
        lastUpdate: '2024-01-22',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['سيارات', 'OBD-II', 'GPS'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=obd2-forensics-tutorial'
    },
    {
        id: 'discord-investigation-suite',
        name: 'Discord Investigation Suite',
        category: 'email-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Windows'],
        description: 'أداة لتحليل خوادم Discord لجمع الرسائل، الملفات، المستخدمين، والنشاطات المشبوهة',
        features: [
            'استخراج سجلات الدردشة',
            'تحليل الملفات المرفقة',
            'استخراج روابط الترحيب والدعوة',
            'ربط الحسابات بعناوين IP'
        ],
        downloadUrl: 'https://github.com/DiscordForensics/discord-investigation-suite',
        officialUrl: 'https://github.com/DiscordForensics/discord-investigation-suite',
        documentation: 'https://github.com/DiscordForensics/discord-investigation-suite/blob/main/README.md',
        price: 'مجاني',
        rating: 4.3,
        downloads: '20K+',
        lastUpdate: '2024-01-28',
        image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=250&fit=crop',
        tags: ['Discord', 'دردشة', 'تحقيق'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=discord-investigation-tutorial'
    },
    {
        id: 'steam-analysis-tools',
        name: 'Steam Analysis Tools',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Windows'],
        description: 'أدوات لتحليل سجلات Steam (ألعاب، محادثات، مبيعات، حسابات)',
        features: [
            'تحليل ملفات logs وconfig',
            'استخراج تاريخ الألعاب واللعب',
            'تحليل محفظة Steam وشراء العملات',
            'ربط الحسابات بعناوين IP'
        ],
        downloadUrl: 'https://github.com/SteamForensics/steam-analysis-tools',
        officialUrl: 'https://github.com/SteamForensics/steam-analysis-tools',
        documentation: 'https://github.com/SteamForensics/steam-analysis-tools/blob/main/README.md',
        price: 'مجاني',
        rating: 4.0,
        downloads: '18K+',
        lastUpdate: '2024-01-18',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['Steam', 'ألعاب', 'تحليل سجلات'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=steam-analysis-tutorial'
    },
    {
        id: 'game-forensics-toolkit',
        name: 'Game Forensics Toolkit',
        category: 'computer-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Linux'],
        description: 'مجموعة أدوات لتحليل بيانات الألعاب (Fortnite, GTA, Valorant) لاستخراج الأدلة الرقمية',
        features: [
            'تحليل ملفات الإعدادات والسجلات',
            'استخراج معلومات الحسابات',
            'تحليل المسارات والحركة داخل اللعبة',
            'ربط الألعاب بالأجهزة والشبكات'
        ],
        downloadUrl: 'https://github.com/GameForensics/game-forensics-toolkit',
        officialUrl: 'https://github.com/GameForensics/game-forensics-toolkit',
        documentation: 'https://github.com/GameForensics/game-forensics-toolkit/blob/main/README.md',
        price: 'مجاني',
        rating: 4.1,
        downloads: '15K+',
        lastUpdate: '2024-01-20',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['ألعاب', 'تحليل سجلات', 'الواقع الافتراضي'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=game-forensics-tutorial'
    },
    {
        id: 'vrf-forensics-toolkit',
        name: 'VR Forensics Toolkit',
        category: 'computer-forensics',
        type: 'تجريبي',
        platforms: ['Python', 'Windows'],
        description: 'أدوات تجريبية لتحليل البيئات الافتراضية (Meta Horizon, VRChat) لجمع الأدلة الرقمية',
        features: [
            'تسجيل نشاط المستخدم في VR',
            'تحليل التفاعلات والصوت',
            'استخراج الملفات المخزنة في VR',
            'ربط الحسابات بعناوين IP'
        ],
        downloadUrl: 'https://github.com/VR-Forensics/vr-forensics-toolkit',
        officialUrl: 'https://github.com/VR-Forensics/vr-forensics-toolkit',
        documentation: 'https://github.com/VR-Forensics/vr-forensics-toolkit/blob/main/README.md',
        price: 'مجاني',
        rating: 3.9,
        downloads: '5K+',
        lastUpdate: '2024-01-15',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['واقع افتراضي', 'VR', 'تحقيق'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=vr-forensics-tutorial'
    },
    {
        id: 'android-spyware-detector',
        name: 'Android Spyware Detector',
        category: 'mobile-forensics',
        type: 'مفتوح المصدر',
        platforms: ['Android', 'Linux'],
        description: 'أداة لفحص الأجهزة المحمولة لاكتشاف البرمجيات الخبيثة والمراقبة الخفية',
        features: [
            'فحص التطبيقات المشبوهة',
            'تحليل الصلاحيات المطلوبة',
            'كشف برامج التجسس والتسجيل',
            'تحليل سجلات الشبكة'
        ],
        downloadUrl: 'https://github.com/Android-Spyware-Detector/spyware-detector',
        officialUrl: 'https://github.com/Android-Spyware-Detector/spyware-detector',
        documentation: 'https://github.com/Android-Spyware-Detector/spyware-detector/blob/main/README.md',
        price: 'مجاني',
        rating: 4.3,
        downloads: '50K+',
        lastUpdate: '2024-01-25',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=250&fit=crop',
        tags: ['أندرويد', 'تجسس', 'برمجة خبيثة'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=android-spyware-tutorial'
    },
    {
        id: 'iphone-backup-extractor',
        name: 'iPhone Backup Extractor',
        category: 'mobile-forensics',
        type: 'مجاني',
        platforms: ['Windows', 'macOS'],
        description: 'أداة لاستخراج وتحليل النسخ الاحتياطية لـ iPhone من iTunes وiCloud',
        features: [
            'استخراج الرسائل، الصور، المكالمات',
            'تحليل ملفات SQLite من النسخ الاحتياطية',
            'عرض بيانات التطبيقات',
            'دعم iOS 12-17'
        ],
        downloadUrl: 'https://www.iphonebackupextractor.com/',
        officialUrl: 'https://www.iphonebackupextractor.com/',
        documentation: 'https://www.iphonebackupextractor.com/help/',
        price: 'مجاني (نسخة أساسية)',
        rating: 4.6,
        downloads: '1M+',
        lastUpdate: '2024-02-01',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=250&fit=crop',
        tags: ['آيفون', 'نسخ احتياطي', 'تحليل بيانات'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=iphone-backup-tutorial'
    },
    {
        id: 'imazing-forensic',
        name: 'iMazing Forensic',
        category: 'mobile-forensics',
        type: 'تجاري',
        platforms: ['Windows', 'macOS'],
        description: 'أداة تجارية متقدمة لاستخراج بيانات iPhone دون الحاجة لفك التشفير',
        features: [
            'استخراج بيانات من النسخ الاحتياطية',
            'تحليل تطبيقات مثل WhatsApp وTelegram',
            'عرض بيانات الموقع والاتصالات',
            'دعم iOS 16+ وFace ID'
        ],
        downloadUrl: 'https://imazing.com/forensic',
        officialUrl: 'https://imazing.com/',
        documentation: 'https://imazing.com/support/forensic',
        price: '$399',
        rating: 4.7,
        downloads: '50K+',
        lastUpdate: '2024-02-03',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=250&fit=crop',
        tags: ['آيفون', 'تحليل بيانات', 'لا فك تشفير'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=imazing-forensic-tutorial'
    },
    {
        id: 'deepware-scanner',
        name: 'Deepware Scanner',
        category: 'malware-analysis',
        type: 'مجاني',
        platforms: ['Web'],
        description: 'أداة مجانية لكشف الفيديوهات المزيفة (Deepfakes) باستخدام الذكاء الاصطناعي',
        features: [
            'رفع فيديو وتحليله تلقائيًا',
            'تحديد درجة التزوير',
            'عرض النقاط المشبوهة في الوجه',
            'دعم فيديوهات MP4, MOV'
        ],
        downloadUrl: 'https://deepware.ai/scanner/',
        officialUrl: 'https://deepware.ai/',
        documentation: 'https://deepware.ai/docs/',
        price: 'مجاني',
        rating: 4.5,
        downloads: '500K+',
        lastUpdate: '2024-02-05',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['Deepfake', 'كشف تزوير', 'ذكاء اصطناعي'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=deepware-scanner-tutorial'
    },
    {
        id: 'faceforensics++',
        name: 'FaceForensics++',
        category: 'malware-analysis',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Linux'],
        description: 'مجموعة بيانات وأدوات مفتوحة المصدر لتحليل تلاعب الوجوه في الفيديوهات',
        features: [
            'تدريب نماذج AI لكشف التزوير',
            'تحليل التغييرات الدقيقة في الوجه',
            'دعم فيديوهات مزيفة من FaceSwap, DeepFaceLab',
            'مصدر بيانات مفتوح'
        ],
        downloadUrl: 'https://github.com/ondyari/FaceForensics',
        officialUrl: 'https://faceforensics.github.io/',
        documentation: 'https://github.com/ondyari/FaceForensics#readme',
        price: 'مجاني',
        rating: 4.7,
        downloads: '200K+',
        lastUpdate: '2024-01-28',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['Deepfake', 'تحليل وجه', 'ذكاء اصطناعي'],
        difficulty: 'متقدم',
        tutorial: 'https://www.youtube.com/watch?v=faceforensics-tutorial'
    },
    {
        id: 'deeperforensics',
        name: 'DeeperForensics',
        category: 'malware-analysis',
        type: 'مفتوح المصدر',
        platforms: ['Python', 'Linux'],
        description: 'نموذج تعلم آلي متقدم لكشف Deepfakes بدقة عالية',
        features: [
            'تحليل تصرفات الوجه والعينين',
            'كشف عدم تناسق الإضاءة',
            'دعم فيديوهات طويلة',
            'معدل دقة > 95%'
        ],
        downloadUrl: 'https://github.com/deeperforensics/deeperforensics',
        officialUrl: 'https://github.com/deeperforensics/deeperforensics',
        documentation: 'https://github.com/deeperforensics/deeperforensics/blob/main/README.md',
        price: 'مجاني',
        rating: 4.6,
        downloads: '100K+',
        lastUpdate: '2024-01-20',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['Deepfake', 'تحليل فيديو', 'ذكاء اصطناعي'],
        difficulty: 'متخصص',
        tutorial: 'https://www.youtube.com/watch?v=deeperforensics-tutorial'
    },
    {
        id: 'microsoft-video-authenticator',
        name: 'Microsoft Video Authenticator',
        category: 'malware-analysis',
        type: 'مجاني',
        platforms: ['Web', 'Windows'],
        description: 'أداة رسمية من مايكروسوفت لكشف التلاعب في الفيديوهات والصور',
        features: [
            'تحليل الفيديوهات مباشرة في المتصفح',
            'كشف التلاعب بالوجه والصوت',
            'عرض تقرير تحليل موثوق',
            'مدعوم من Microsoft Research'
        ],
        downloadUrl: 'https://www.microsoft.com/en-us/research/project/video-authenticator/',
        officialUrl: 'https://www.microsoft.com/en-us/research/project/video-authenticator/',
        documentation: 'https://www.microsoft.com/en-us/research/publication/video-authenticator/',
        price: 'مجاني',
        rating: 4.6,
        downloads: '300K+',
        lastUpdate: '2024-02-02',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
        tags: ['Deepfake', 'كشف تزوير', 'مايكروسوفت'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=microsoft-video-authenticator-tutorial'
    },
    {
        id: 'mailxaminer',
        name: 'MailXaminer',
        category: 'email-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'أداة متقدمة لتحليل وفحص رسائل البريد الإلكتروني من مختلف المنصات',
        features: [
            'دعم أكثر من 20 تنسيق بريد إلكتروني',
            'استعادة الرسائل المحذوفة',
            'تحليل البيانات الوصفية للرسائل',
            'بحث متقدم ومرشحات',
            'إنشاء تقارير تفصيلية'
        ],
        downloadUrl: 'https://www.mailxaminer.com/',
        officialUrl: 'https://www.mailxaminer.com/',
        documentation: 'https://www.mailxaminer.com/support/',
        price: '$399',
        rating: 4.5,
        downloads: '30K+',
        lastUpdate: '2024-01-18',
        image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=250&fit=crop',
        tags: ['بريد إلكتروني', 'استعادة رسائل', 'تحليل metadata'],
        difficulty: 'مبتدئ',
        tutorial: 'https://www.youtube.com/watch?v=mailxaminer-tutorial'
    },
    {
        id: 'aid4mail',
        name: 'Aid4Mail',
        category: 'email-forensics',
        type: 'تجاري',
        platforms: ['Windows', 'Linux'],
        description: 'أداة تحويل وتحليل البريد الإلكتروني بين تنسيقات مختلفة مع دعم التشفير',
        features: [
            'تحويل PST, OST, EML, MSG, MBOX',
            'استخراج المرفقات',
            'تحليل التشفير (S/MIME, PGP)',
            'دعم التوافق مع EnCase وFTK'
        ],
        downloadUrl: 'https://www.aid4mail.com/',
        officialUrl: 'https://www.aid4mail.com/',
        documentation: 'https://www.aid4mail.com/support/',
        price: '$499',
        rating: 4.4,
        downloads: '25K+',
        lastUpdate: '2024-01-15',
        image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=250&fit=crop',
        tags: ['بريد إلكتروني', 'تحويل تنسيقات', 'تحليل تشفير'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=aid4mail-tutorial'
    },
    {
        id: 'kernel-email-forensics',
        name: 'Kernel Email Forensics',
        category: 'email-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'أداة استعادة رسائل البريد الإلكتروني المحذوفة من Outlook وExchange',
        features: [
            'استعادة من PST, OST, EDB',
            'تحليل سجلات الحذف',
            'استخراج المرفقات المحذوفة',
            'دعم البحث المتقدم'
        ],
        downloadUrl: 'https://www.nucleustechnologies.com/email-forensics/',
        officialUrl: 'https://www.nucleustechnologies.com/',
        documentation: 'https://www.nucleustechnologies.com/email-forensics/help/',
        price: '$299',
        rating: 4.3,
        downloads: '20K+',
        lastUpdate: '2024-01-12',
        image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=250&fit=crop',
        tags: ['بريد إلكتروني', 'استعادة محذوفة', 'Outlook'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=kernel-email-forensics-tutorial'
    },
    {
        id: 'digital-detective-netanalysis',
        name: 'Digital Detective NetAnalysis',
        category: 'email-forensics',
        type: 'تجاري',
        platforms: ['Windows'],
        description: 'أداة تحليل متصفحات الإنترنت وسجلات البريد الإلكتروني والأنشطة الرقمية',
        features: [
            'تحليل ملفات Internet Explorer, Firefox, Chrome',
            'استعادة سجلات التصفح المحذوفة',
            'تحليل ملفات البريد الإلكتروني',
            'عرض الجدول الزمني للنشاط'
        ],
        downloadUrl: 'https://www.digitaldetective.net/netanalysis/',
        officialUrl: 'https://www.digitaldetective.net/',
        documentation: 'https://www.digitaldetective.net/netanalysis/help/',
        price: '$499',
        rating: 4.2,
        downloads: '15K+',
        lastUpdate: '2024-01-10',
        image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=250&fit=crop',
        tags: ['متصفحات', 'سجلات تصفح', 'بريد إلكتروني'],
        difficulty: 'متوسط',
        tutorial: 'https://www.youtube.com/watch?v=digital-detective-netanalysis-tutorial'
    }
];

// Operating Systems Data
const operatingSystems = [
    {
        id: 'sift',
        name: 'SIFT Workstation',
        type: 'توزيعة Linux متخصصة',
        description: 'توزيعة أوبنتو متخصصة في التحقيق الجنائي الرقمي من SANS',
        features: [
            'أكثر من 300 أداة جنائية مثبتة مسبقاً',
            'بيئة تطوير متكاملة',
            'دعم تحليل الذاكرة والشبكات',
            'واجهة رسومية سهلة الاستخدام'
        ],
        downloadUrl: 'https://www.sans.org/tools/sift-workstation/',
        price: 'مجاني',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=250&fit=crop'
    },
    {
        id: 'kali-linux',
        name: 'Kali Linux',
        type: 'توزيعة Linux أمنية',
        description: 'التوزيعة الأكثر شهرة لاختبار الاختراق والتحقيق الجنائي',
        features: [
            'أكثر من 600 أداة أمنية',
            'دعم ARM architecture',
            'تحديثات أمنية مستمرة',
            'بيئة عمل متكاملة للأمان السيبراني'
        ],
        downloadUrl: 'https://www.kali.org/get-kali/',
        price: 'مجاني',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=400&h=250&fit=crop'
    },
    {
        id: 'caine',
        name: 'CAINE Linux',
        type: 'بيئة تحقيق جنائي',
        description: 'Computer Aided Investigative Environment - بيئة متكاملة للتحقيق',
        features: [
            'واجهة سهلة للمبتدئين',
            'أدوات تحليل متقدمة',
            'دعم الأقراص المشفرة',
            'إمكانيات الشبكة المباشرة'
        ],
        downloadUrl: 'https://www.caine-live.net/',
        price: 'مجاني',
        rating: 4.5,
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=250&fit=crop'
    }
];

// Learning Resources
const learningResources = [
    {
        category: 'كتب ومراجع',
        icon: 'fas fa-book',
        items: [
            {
                title: 'Digital Forensics with Open Source Tools',
                author: 'Cory Altheide',
                description: 'دليل شامل لاستخدام الأدوات مفتوحة المصدر في التحقيق الجنائي',
                url: '#',
                rating: 4.6
            },
            {
                title: 'The Art of Memory Forensics',
                author: 'Michael Ligh',
                description: 'الكتاب الأساسي لتعلم تحليل الذاكرة باستخدام Volatility',
                url: '#',
                rating: 4.8
            },
            {
                title: 'Network Forensics: Tracking Hackers',
                author: 'Sherri Davidoff',
                description: 'تعلم تقنيات تتبع المهاجمين عبر الشبكات',
                url: '#',
                rating: 4.5
            }
        ]
    },
    {
        category: 'دورات تدريبية',
        icon: 'fas fa-video',
        items: [
            {
                title: 'SANS FOR508: Advanced Incident Response',
                provider: 'SANS Institute',
                description: 'دورة متقدمة في الاستجابة للحوادث والتحقيق الجنائي',
                url: '#',
                duration: '6 أيام',
                rating: 4.9
            },
            {
                title: 'Computer Forensics Fundamentals',
                provider: 'Cybrary',
                description: 'أساسيات التحقيق الجنائي الرقمي للمبتدئين',
                url: '#',
                duration: '8 ساعات',
                rating: 4.4
            },
            {
                title: 'Mobile Device Security and Forensics',
                provider: 'Udemy',
                description: 'تعلم تحليل الأجهزة المحمولة والأمان',
                url: '#',
                duration: '12 ساعة',
                rating: 4.3
            }
        ]
    },
    {
        category: 'شهادات احترافية',
        icon: 'fas fa-certificate',
        items: [
            {
                title: 'CHFI - Computer Hacking Forensic Investigator',
                provider: 'EC-Council',
                description: 'شهادة معترف بها عالمياً في التحقيق الجنائي الرقمي',
                url: '#',
                difficulty: 'متوسط',
                rating: 4.7
            },
            {
                title: 'GCFA - GIAC Certified Forensic Analyst',
                provider: 'SANS/GIAC',
                description: 'شهادة متقدمة في تحليل الأدلة الرقمية',
                url: '#',
                difficulty: 'متقدم',
                rating: 4.9
            },
            {
                title: 'EnCE - EnCase Certified Examiner',
                provider: 'Guidance Software',
                description: 'شهادة متخصصة في استخدام أداة EnCase',
                url: '#',
                difficulty: 'متقدم',
                rating: 4.8
            }
        ]
    }
];

// Statistics and Counters
const siteStats = {
    totalTools: forensicsTools.length,
    totalCategories: categories.length,
    totalResources: learningResources.reduce((acc, cat) => acc + cat.items.length, 0),
    lastUpdated: '2025-04-05'
};

// Export data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        categories,
        forensicsTools,
        operatingSystems,
        learningResources,
        siteStats
    };
}